# Generated by Django 2.2.16 on 2020-12-23 15:15

from django.db import migrations, models
import sberbank.models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0007_auto_20190826_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'WEB'), (2, 'APPLE'), (3, 'GOOGLE'), (4, 'RECURRENT')], db_index=True, default=sberbank.models.Method(0), verbose_name='method'),
        ),
    ]
